server.port=8888
spring.application.name=config-server

# Config Server Local Profile
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/Users/INFINIX/Desktop/OmniChargeLogging/OmniChargeLogging/central-config/,classpath:/central-config/

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Actuator - expose Prometheus metrics endpoint
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

